"""Generate docs/tools.md from the live tool/prompt/resource catalogue of the server.

Run: python docs/generate_tools_md.py
"""

from __future__ import annotations

import asyncio
from pathlib import Path

from mcp import Client

from open_med_mcp.server import create_server

OUT = Path(__file__).resolve().parent / "tools.md"


def _type(schema: dict) -> str:
    if "enum" in schema:
        return " \\| ".join(f"`{v}`" for v in schema["enum"])
    if "anyOf" in schema:
        return " \\| ".join(_type(s) for s in schema["anyOf"] if s.get("type") != "null") or "any"
    if "$ref" in schema:
        return schema["$ref"].split("/")[-1]
    t = schema.get("type", "any")
    if t == "array":
        return f"array of {_type(schema.get('items', {}))}"
    return t


async def main() -> None:
    server = create_server()
    lines = [
        "# Tool reference",
        "",
        "Generated by `docs/generate_tools_md.py` from the running server. Paths are resolved against the workspace; all coordinates are native voxel indices (see [coordinates.md](coordinates.md)).",
        "",
    ]
    async with Client(server, raise_exceptions=True) as c:
        tools = (await c.list_tools()).tools
        lines += ["## Tools", ""]
        for t in tools:
            lines += [f"### `{t.name}`", "", (t.description or "").strip(), ""]
            schema = t.input_schema or {}
            props = schema.get("properties", {})
            required = set(schema.get("required", []))
            if props:
                lines += ["| parameter | type | default | description |", "|---|---|---|---|"]
                for name, ps in props.items():
                    default = (
                        "*required*"
                        if name in required
                        else f"`{ps.get('default')}`"
                        if "default" in ps
                        else ""
                    )
                    lines.append(f"| `{name}` | {_type(ps)} | {default} | {ps.get('description', '')} |")
                lines.append("")
            ann = t.annotations
            if ann and ann.read_only_hint:
                lines += ["*Read-only.*", ""]
        prompts = (await c.list_prompts()).prompts
        lines += ["## Prompts (guidelines)", "", "| prompt | description |", "|---|---|"]
        for p in prompts:
            lines.append(f"| `{p.name}` | {(p.description or '').strip()} |")
        lines += ["", "Every prompt accepts optional `image` and `goal` arguments.", ""]
        templates = (await c.list_resource_templates()).resource_templates
        resources = (await c.list_resources()).resources
        lines += ["## Resources", "", "| uri | description |", "|---|---|"]
        for r in resources:
            lines.append(f"| `{r.uri}` | {(r.description or '').strip()} |")
        for r in templates:
            lines.append(f"| `{r.uri_template}` | {(r.description or '').strip()} |")
        lines.append("")
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print("wrote", OUT, "with", len(tools), "tools")


if __name__ == "__main__":
    asyncio.run(main())
